//
//  Player.swift
//  Player
//
//  Created by Shane Whitehead on 4/10/18.
//  Copyright © 2018 KaiZen Enterprises. All rights reserved.
//
//  Generated by PaintCode
//  http://www.paintcodeapp.com
//



import UIKit

public class Player : NSObject {

    //// Drawing Methods

    @objc dynamic public class func drawWatcher(frame: CGRect = CGRect(x: 0, y: 0, width: 200, height: 200)) {
        //// General Declarations
        // This non-generic function dramatically improves compilation times of complex expressions.
        func fastFloor(_ x: CGFloat) -> CGFloat { return floor(x) }

        //// Color Declarations
        let fillColor = UIColor(red: 0.000, green: 0.000, blue: 0.000, alpha: 1.000)


        //// Subframes
        let surface1: CGRect = CGRect(x: frame.minX + fastFloor(frame.width * 0.01981 - 0.46) + 0.96, y: frame.minY + fastFloor(frame.height * 0.24703 + 0.09) + 0.41, width: fastFloor(frame.width * 0.98019 + 0.46) - fastFloor(frame.width * 0.01981 - 0.46) - 0.92, height: fastFloor(frame.height * 0.75297 - 0.09) - fastFloor(frame.height * 0.24703 + 0.09) + 0.19)


        //// surface1
        //// Bezier Drawing
        let bezierPath = UIBezierPath()
        bezierPath.move(to: CGPoint(x: surface1.minX + 0.37325 * surface1.width, y: surface1.minY + 0.00000 * surface1.height))
        bezierPath.addCurve(to: CGPoint(x: surface1.minX + 0.00469 * surface1.width, y: surface1.minY + 0.45658 * surface1.height), controlPoint1: CGPoint(x: surface1.minX + 0.16524 * surface1.width, y: surface1.minY + 0.10717 * surface1.height), controlPoint2: CGPoint(x: surface1.minX + 0.01298 * surface1.width, y: surface1.minY + 0.44076 * surface1.height))
        bezierPath.addCurve(to: CGPoint(x: surface1.minX + 0.00469 * surface1.width, y: surface1.minY + 0.50744 * surface1.height), controlPoint1: CGPoint(x: surface1.minX + -0.00156 * surface1.width, y: surface1.minY + 0.47239 * surface1.height), controlPoint2: CGPoint(x: surface1.minX + -0.00156 * surface1.width, y: surface1.minY + 0.49163 * surface1.height))
        bezierPath.addCurve(to: CGPoint(x: surface1.minX + 0.50000 * surface1.width, y: surface1.minY + 1.00000 * surface1.height), controlPoint1: CGPoint(x: surface1.minX + 0.01509 * surface1.width, y: surface1.minY + 0.53133 * surface1.height), controlPoint2: CGPoint(x: surface1.minX + 0.22960 * surface1.width, y: surface1.minY + 1.00000 * surface1.height))
        bezierPath.addCurve(to: CGPoint(x: surface1.minX + 0.99531 * surface1.width, y: surface1.minY + 0.51241 * surface1.height), controlPoint1: CGPoint(x: surface1.minX + 0.77040 * surface1.width, y: surface1.minY + 1.00000 * surface1.height), controlPoint2: CGPoint(x: surface1.minX + 0.98491 * surface1.width, y: surface1.minY + 0.53226 * surface1.height))
        bezierPath.addCurve(to: CGPoint(x: surface1.minX + 0.99531 * surface1.width, y: surface1.minY + 0.45658 * surface1.height), controlPoint1: CGPoint(x: surface1.minX + 1.00156 * surface1.width, y: surface1.minY + 0.49659 * surface1.height), controlPoint2: CGPoint(x: surface1.minX + 1.00156 * surface1.width, y: surface1.minY + 0.47239 * surface1.height))
        bezierPath.addCurve(to: CGPoint(x: surface1.minX + 0.62675 * surface1.width, y: surface1.minY + 0.00000 * surface1.height), controlPoint1: CGPoint(x: surface1.minX + 0.98702 * surface1.width, y: surface1.minY + 0.44076 * surface1.height), controlPoint2: CGPoint(x: surface1.minX + 0.83476 * surface1.width, y: surface1.minY + 0.10717 * surface1.height))
        bezierPath.addCurve(to: CGPoint(x: surface1.minX + 0.72880 * surface1.width, y: surface1.minY + 0.36476 * surface1.height), controlPoint1: CGPoint(x: surface1.minX + 0.68915 * surface1.width, y: surface1.minY + 0.07940 * surface1.height), controlPoint2: CGPoint(x: surface1.minX + 0.72880 * surface1.width, y: surface1.minY + 0.20999 * surface1.height))
        bezierPath.addCurve(to: CGPoint(x: surface1.minX + 0.50000 * surface1.width, y: surface1.minY + 0.80149 * surface1.height), controlPoint1: CGPoint(x: surface1.minX + 0.72880 * surface1.width, y: surface1.minY + 0.60701 * surface1.height), controlPoint2: CGPoint(x: surface1.minX + 0.62691 * surface1.width, y: surface1.minY + 0.80149 * surface1.height))
        bezierPath.addCurve(to: CGPoint(x: surface1.minX + 0.27120 * surface1.width, y: surface1.minY + 0.36476 * surface1.height), controlPoint1: CGPoint(x: surface1.minX + 0.37309 * surface1.width, y: surface1.minY + 0.80149 * surface1.height), controlPoint2: CGPoint(x: surface1.minX + 0.27120 * surface1.width, y: surface1.minY + 0.60701 * surface1.height))
        bezierPath.addCurve(to: CGPoint(x: surface1.minX + 0.37325 * surface1.width, y: surface1.minY + 0.00000 * surface1.height), controlPoint1: CGPoint(x: surface1.minX + 0.27120 * surface1.width, y: surface1.minY + 0.21386 * surface1.height), controlPoint2: CGPoint(x: surface1.minX + 0.31296 * surface1.width, y: surface1.minY + 0.07940 * surface1.height))
        bezierPath.close()
        bezierPath.move(to: CGPoint(x: surface1.minX + 0.50000 * surface1.width, y: surface1.minY + 0.16625 * surface1.height))
        bezierPath.addCurve(to: CGPoint(x: surface1.minX + 0.39600 * surface1.width, y: surface1.minY + 0.36476 * surface1.height), controlPoint1: CGPoint(x: surface1.minX + 0.44280 * surface1.width, y: surface1.minY + 0.16625 * surface1.height), controlPoint2: CGPoint(x: surface1.minX + 0.39600 * surface1.width, y: surface1.minY + 0.25558 * surface1.height))
        bezierPath.addCurve(to: CGPoint(x: surface1.minX + 0.50000 * surface1.width, y: surface1.minY + 0.56328 * surface1.height), controlPoint1: CGPoint(x: surface1.minX + 0.39600 * surface1.width, y: surface1.minY + 0.47395 * surface1.height), controlPoint2: CGPoint(x: surface1.minX + 0.44280 * surface1.width, y: surface1.minY + 0.56328 * surface1.height))
        bezierPath.addCurve(to: CGPoint(x: surface1.minX + 0.60400 * surface1.width, y: surface1.minY + 0.36476 * surface1.height), controlPoint1: CGPoint(x: surface1.minX + 0.55720 * surface1.width, y: surface1.minY + 0.56328 * surface1.height), controlPoint2: CGPoint(x: surface1.minX + 0.60400 * surface1.width, y: surface1.minY + 0.47395 * surface1.height))
        bezierPath.addCurve(to: CGPoint(x: surface1.minX + 0.50000 * surface1.width, y: surface1.minY + 0.16625 * surface1.height), controlPoint1: CGPoint(x: surface1.minX + 0.60400 * surface1.width, y: surface1.minY + 0.25558 * surface1.height), controlPoint2: CGPoint(x: surface1.minX + 0.55720 * surface1.width, y: surface1.minY + 0.16625 * surface1.height))
        bezierPath.close()
        bezierPath.move(to: CGPoint(x: surface1.minX + 0.50000 * surface1.width, y: surface1.minY + 0.24566 * surface1.height))
        bezierPath.addCurve(to: CGPoint(x: surface1.minX + 0.56240 * surface1.width, y: surface1.minY + 0.36476 * surface1.height), controlPoint1: CGPoint(x: surface1.minX + 0.53469 * surface1.width, y: surface1.minY + 0.24566 * surface1.height), controlPoint2: CGPoint(x: surface1.minX + 0.56240 * surface1.width, y: surface1.minY + 0.29854 * surface1.height))
        bezierPath.addCurve(to: CGPoint(x: surface1.minX + 0.50000 * surface1.width, y: surface1.minY + 0.48387 * surface1.height), controlPoint1: CGPoint(x: surface1.minX + 0.56240 * surface1.width, y: surface1.minY + 0.43099 * surface1.height), controlPoint2: CGPoint(x: surface1.minX + 0.53469 * surface1.width, y: surface1.minY + 0.48387 * surface1.height))
        bezierPath.addCurve(to: CGPoint(x: surface1.minX + 0.43760 * surface1.width, y: surface1.minY + 0.36476 * surface1.height), controlPoint1: CGPoint(x: surface1.minX + 0.46531 * surface1.width, y: surface1.minY + 0.48387 * surface1.height), controlPoint2: CGPoint(x: surface1.minX + 0.43760 * surface1.width, y: surface1.minY + 0.43099 * surface1.height))
        bezierPath.addCurve(to: CGPoint(x: surface1.minX + 0.50000 * surface1.width, y: surface1.minY + 0.24566 * surface1.height), controlPoint1: CGPoint(x: surface1.minX + 0.43760 * surface1.width, y: surface1.minY + 0.29854 * surface1.height), controlPoint2: CGPoint(x: surface1.minX + 0.46531 * surface1.width, y: surface1.minY + 0.24566 * surface1.height))
        bezierPath.close()
        fillColor.setFill()
        bezierPath.fill()
    }

    @objc dynamic public class func drawFailed(frame: CGRect = CGRect(x: 0, y: 0, width: 50, height: 50)) {
        //// General Declarations
        // This non-generic function dramatically improves compilation times of complex expressions.
        func fastFloor(_ x: CGFloat) -> CGFloat { return floor(x) }

        //// Color Declarations
        let fillColor = UIColor(red: 0.000, green: 0.000, blue: 0.000, alpha: 1.000)


        //// Subframes
        let group: CGRect = CGRect(x: frame.minX + fastFloor(frame.width * 0.06000 + 0.5), y: frame.minY + fastFloor(frame.height * 0.06000 + 0.5), width: fastFloor(frame.width * 0.94000 + 0.5) - fastFloor(frame.width * 0.06000 + 0.5), height: fastFloor(frame.height * 0.94000 + 0.5) - fastFloor(frame.height * 0.06000 + 0.5))


        //// Group
        //// Bezier Drawing
        let bezierPath = UIBezierPath()
        bezierPath.move(to: CGPoint(x: group.minX + 0.50000 * group.width, y: group.minY + 0.00000 * group.height))
        bezierPath.addCurve(to: CGPoint(x: group.minX + 0.00000 * group.width, y: group.minY + 0.50000 * group.height), controlPoint1: CGPoint(x: group.minX + 0.22413 * group.width, y: group.minY + 0.00000 * group.height), controlPoint2: CGPoint(x: group.minX + 0.00000 * group.width, y: group.minY + 0.22413 * group.height))
        bezierPath.addCurve(to: CGPoint(x: group.minX + 0.50000 * group.width, y: group.minY + 1.00000 * group.height), controlPoint1: CGPoint(x: group.minX + 0.00000 * group.width, y: group.minY + 0.77587 * group.height), controlPoint2: CGPoint(x: group.minX + 0.22413 * group.width, y: group.minY + 1.00000 * group.height))
        bezierPath.addCurve(to: CGPoint(x: group.minX + 1.00000 * group.width, y: group.minY + 0.50000 * group.height), controlPoint1: CGPoint(x: group.minX + 0.77587 * group.width, y: group.minY + 1.00000 * group.height), controlPoint2: CGPoint(x: group.minX + 1.00000 * group.width, y: group.minY + 0.77587 * group.height))
        bezierPath.addCurve(to: CGPoint(x: group.minX + 0.50000 * group.width, y: group.minY + 0.00000 * group.height), controlPoint1: CGPoint(x: group.minX + 1.00000 * group.width, y: group.minY + 0.22413 * group.height), controlPoint2: CGPoint(x: group.minX + 0.77587 * group.width, y: group.minY + 0.00000 * group.height))
        bezierPath.close()
        bezierPath.move(to: CGPoint(x: group.minX + 0.50000 * group.width, y: group.minY + 0.04545 * group.height))
        bezierPath.addCurve(to: CGPoint(x: group.minX + 0.95455 * group.width, y: group.minY + 0.50000 * group.height), controlPoint1: CGPoint(x: group.minX + 0.75131 * group.width, y: group.minY + 0.04545 * group.height), controlPoint2: CGPoint(x: group.minX + 0.95455 * group.width, y: group.minY + 0.24869 * group.height))
        bezierPath.addCurve(to: CGPoint(x: group.minX + 0.50000 * group.width, y: group.minY + 0.95455 * group.height), controlPoint1: CGPoint(x: group.minX + 0.95455 * group.width, y: group.minY + 0.75131 * group.height), controlPoint2: CGPoint(x: group.minX + 0.75131 * group.width, y: group.minY + 0.95455 * group.height))
        bezierPath.addCurve(to: CGPoint(x: group.minX + 0.04545 * group.width, y: group.minY + 0.50000 * group.height), controlPoint1: CGPoint(x: group.minX + 0.24869 * group.width, y: group.minY + 0.95455 * group.height), controlPoint2: CGPoint(x: group.minX + 0.04545 * group.width, y: group.minY + 0.75131 * group.height))
        bezierPath.addCurve(to: CGPoint(x: group.minX + 0.50000 * group.width, y: group.minY + 0.04545 * group.height), controlPoint1: CGPoint(x: group.minX + 0.04545 * group.width, y: group.minY + 0.24869 * group.height), controlPoint2: CGPoint(x: group.minX + 0.24869 * group.width, y: group.minY + 0.04545 * group.height))
        bezierPath.close()
        bezierPath.move(to: CGPoint(x: group.minX + 0.31796 * group.width, y: group.minY + 0.29523 * group.height))
        bezierPath.addLine(to: CGPoint(x: group.minX + 0.31797 * group.width, y: group.minY + 0.29523 * group.height))
        bezierPath.addCurve(to: CGPoint(x: group.minX + 0.29524 * group.width, y: group.minY + 0.31796 * group.height), controlPoint1: CGPoint(x: group.minX + 0.30541 * group.width, y: group.minY + 0.29523 * group.height), controlPoint2: CGPoint(x: group.minX + 0.29524 * group.width, y: group.minY + 0.30541 * group.height))
        bezierPath.addCurve(to: CGPoint(x: group.minX + 0.30218 * group.width, y: group.minY + 0.33431 * group.height), controlPoint1: CGPoint(x: group.minX + 0.29524 * group.width, y: group.minY + 0.32413 * group.height), controlPoint2: CGPoint(x: group.minX + 0.29774 * group.width, y: group.minY + 0.33003 * group.height))
        bezierPath.addLine(to: CGPoint(x: group.minX + 0.46786 * group.width, y: group.minY + 0.50000 * group.height))
        bezierPath.addLine(to: CGPoint(x: group.minX + 0.30211 * group.width, y: group.minY + 0.66575 * group.height))
        bezierPath.addLine(to: CGPoint(x: group.minX + 0.30207 * group.width, y: group.minY + 0.66580 * group.height))
        bezierPath.addCurve(to: CGPoint(x: group.minX + 0.30150 * group.width, y: group.minY + 0.69793 * group.height), controlPoint1: CGPoint(x: group.minX + 0.29304 * group.width, y: group.minY + 0.67452 * group.height), controlPoint2: CGPoint(x: group.minX + 0.29278 * group.width, y: group.minY + 0.68890 * group.height))
        bezierPath.addCurve(to: CGPoint(x: group.minX + 0.33364 * group.width, y: group.minY + 0.69850 * group.height), controlPoint1: CGPoint(x: group.minX + 0.31022 * group.width, y: group.minY + 0.70696 * group.height), controlPoint2: CGPoint(x: group.minX + 0.32461 * group.width, y: group.minY + 0.70722 * group.height))
        bezierPath.addCurve(to: CGPoint(x: group.minX + 0.33420 * group.width, y: group.minY + 0.69793 * group.height), controlPoint1: CGPoint(x: group.minX + 0.33383 * group.width, y: group.minY + 0.69831 * group.height), controlPoint2: CGPoint(x: group.minX + 0.33402 * group.width, y: group.minY + 0.69812 * group.height))
        bezierPath.addLine(to: CGPoint(x: group.minX + 0.50000 * group.width, y: group.minY + 0.53214 * group.height))
        bezierPath.addLine(to: CGPoint(x: group.minX + 0.66575 * group.width, y: group.minY + 0.69789 * group.height))
        bezierPath.addLine(to: CGPoint(x: group.minX + 0.66580 * group.width, y: group.minY + 0.69793 * group.height))
        bezierPath.addCurve(to: CGPoint(x: group.minX + 0.69793 * group.width, y: group.minY + 0.69850 * group.height), controlPoint1: CGPoint(x: group.minX + 0.67452 * group.width, y: group.minY + 0.70696 * group.height), controlPoint2: CGPoint(x: group.minX + 0.68890 * group.width, y: group.minY + 0.70722 * group.height))
        bezierPath.addCurve(to: CGPoint(x: group.minX + 0.69850 * group.width, y: group.minY + 0.66636 * group.height), controlPoint1: CGPoint(x: group.minX + 0.70696 * group.width, y: group.minY + 0.68978 * group.height), controlPoint2: CGPoint(x: group.minX + 0.70722 * group.width, y: group.minY + 0.67539 * group.height))
        bezierPath.addCurve(to: CGPoint(x: group.minX + 0.69793 * group.width, y: group.minY + 0.66580 * group.height), controlPoint1: CGPoint(x: group.minX + 0.69831 * group.width, y: group.minY + 0.66617 * group.height), controlPoint2: CGPoint(x: group.minX + 0.69812 * group.width, y: group.minY + 0.66598 * group.height))
        bezierPath.addLine(to: CGPoint(x: group.minX + 0.53214 * group.width, y: group.minY + 0.50000 * group.height))
        bezierPath.addLine(to: CGPoint(x: group.minX + 0.69789 * group.width, y: group.minY + 0.33425 * group.height))
        bezierPath.addLine(to: CGPoint(x: group.minX + 0.69783 * group.width, y: group.minY + 0.33430 * group.height))
        bezierPath.addCurve(to: CGPoint(x: group.minX + 0.69839 * group.width, y: group.minY + 0.30216 * group.height), controlPoint1: CGPoint(x: group.minX + 0.70686 * group.width, y: group.minY + 0.32558 * group.height), controlPoint2: CGPoint(x: group.minX + 0.70711 * group.width, y: group.minY + 0.31119 * group.height))
        bezierPath.addCurve(to: CGPoint(x: group.minX + 0.68125 * group.width, y: group.minY + 0.29524 * group.height), controlPoint1: CGPoint(x: group.minX + 0.69392 * group.width, y: group.minY + 0.29753 * group.height), controlPoint2: CGPoint(x: group.minX + 0.68769 * group.width, y: group.minY + 0.29501 * group.height))
        bezierPath.addLine(to: CGPoint(x: group.minX + 0.68126 * group.width, y: group.minY + 0.29524 * group.height))
        bezierPath.addCurve(to: CGPoint(x: group.minX + 0.66570 * group.width, y: group.minY + 0.30216 * group.height), controlPoint1: CGPoint(x: group.minX + 0.67537 * group.width, y: group.minY + 0.29544 * group.height), controlPoint2: CGPoint(x: group.minX + 0.66979 * group.width, y: group.minY + 0.29793 * group.height))
        bezierPath.addLine(to: CGPoint(x: group.minX + 0.50000 * group.width, y: group.minY + 0.46786 * group.height))
        bezierPath.addLine(to: CGPoint(x: group.minX + 0.33425 * group.width, y: group.minY + 0.30211 * group.height))
        bezierPath.addLine(to: CGPoint(x: group.minX + 0.33431 * group.width, y: group.minY + 0.30217 * group.height))
        bezierPath.addCurve(to: CGPoint(x: group.minX + 0.31796 * group.width, y: group.minY + 0.29523 * group.height), controlPoint1: CGPoint(x: group.minX + 0.33003 * group.width, y: group.minY + 0.29774 * group.height), controlPoint2: CGPoint(x: group.minX + 0.32413 * group.width, y: group.minY + 0.29523 * group.height))
        bezierPath.close()
        fillColor.setFill()
        bezierPath.fill()
    }

    @objc dynamic public class func drawSettings(frame: CGRect = CGRect(x: 0, y: 0, width: 50, height: 50)) {
        //// General Declarations
        // This non-generic function dramatically improves compilation times of complex expressions.
        func fastFloor(_ x: CGFloat) -> CGFloat { return floor(x) }

        //// Color Declarations
        let white = UIColor(red: 1.000, green: 1.000, blue: 1.000, alpha: 1.000)


        //// Subframes
        let group: CGRect = CGRect(x: frame.minX + fastFloor(frame.width * 0.04004 + 0.5) + 0, y: frame.minY + fastFloor(frame.height * 0.04000 + 0.5), width: fastFloor(frame.width * 0.95996 - 0.5) - fastFloor(frame.width * 0.04004 + 0.5) + 1, height: fastFloor(frame.height * 0.96000 + 0.5) - fastFloor(frame.height * 0.04000 + 0.5))


        //// Group
        //// Bezier Drawing
        let bezierPath = UIBezierPath()
        bezierPath.move(to: CGPoint(x: group.minX + 0.98178 * group.width, y: group.minY + 0.41785 * group.height))
        bezierPath.addLine(to: CGPoint(x: group.minX + 0.85329 * group.width, y: group.minY + 0.39685 * group.height))
        bezierPath.addCurve(to: CGPoint(x: group.minX + 0.82261 * group.width, y: group.minY + 0.32283 * group.height), controlPoint1: CGPoint(x: group.minX + 0.84577 * group.width, y: group.minY + 0.37107 * group.height), controlPoint2: CGPoint(x: group.minX + 0.83549 * group.width, y: group.minY + 0.34628 * group.height))
        bezierPath.addLine(to: CGPoint(x: group.minX + 0.89762 * group.width, y: group.minY + 0.21593 * group.height))
        bezierPath.addCurve(to: CGPoint(x: group.minX + 0.89519 * group.width, y: group.minY + 0.18807 * group.height), controlPoint1: CGPoint(x: group.minX + 0.90369 * group.width, y: group.minY + 0.20730 * group.height), controlPoint2: CGPoint(x: group.minX + 0.90264 * group.width, y: group.minY + 0.19554 * group.height))
        bezierPath.addLine(to: CGPoint(x: group.minX + 0.81064 * group.width, y: group.minY + 0.10357 * group.height))
        bezierPath.addCurve(to: CGPoint(x: group.minX + 0.78257 * group.width, y: group.minY + 0.10130 * group.height), controlPoint1: CGPoint(x: group.minX + 0.80309 * group.width, y: group.minY + 0.09604 * group.height), controlPoint2: CGPoint(x: group.minX + 0.79122 * group.width, y: group.minY + 0.09507 * group.height))
        bezierPath.addLine(to: CGPoint(x: group.minX + 0.67728 * group.width, y: group.minY + 0.17698 * group.height))
        bezierPath.addCurve(to: CGPoint(x: group.minX + 0.60266 * group.width, y: group.minY + 0.14596 * group.height), controlPoint1: CGPoint(x: group.minX + 0.65360 * group.width, y: group.minY + 0.16389 * group.height), controlPoint2: CGPoint(x: group.minX + 0.62860 * group.width, y: group.minY + 0.15350 * group.height))
        bezierPath.addLine(to: CGPoint(x: group.minX + 0.58025 * group.width, y: group.minY + 0.01800 * group.height))
        bezierPath.addCurve(to: CGPoint(x: group.minX + 0.55883 * group.width, y: group.minY + 0.00000 * group.height), controlPoint1: CGPoint(x: group.minX + 0.57842 * group.width, y: group.minY + 0.00761 * group.height), controlPoint2: CGPoint(x: group.minX + 0.56940 * group.width, y: group.minY + 0.00000 * group.height))
        bezierPath.addLine(to: CGPoint(x: group.minX + 0.43926 * group.width, y: group.minY + 0.00000 * group.height))
        bezierPath.addCurve(to: CGPoint(x: group.minX + 0.41780 * group.width, y: group.minY + 0.01824 * group.height), controlPoint1: CGPoint(x: group.minX + 0.42860 * group.width, y: group.minY + 0.00000 * group.height), controlPoint2: CGPoint(x: group.minX + 0.41951 * group.width, y: group.minY + 0.00772 * group.height))
        bezierPath.addLine(to: CGPoint(x: group.minX + 0.39701 * group.width, y: group.minY + 0.14550 * group.height))
        bezierPath.addCurve(to: CGPoint(x: group.minX + 0.32229 * group.width, y: group.minY + 0.17620 * group.height), controlPoint1: CGPoint(x: group.minX + 0.37092 * group.width, y: group.minY + 0.15300 * group.height), controlPoint2: CGPoint(x: group.minX + 0.34588 * group.width, y: group.minY + 0.16328 * group.height))
        bezierPath.addLine(to: CGPoint(x: group.minX + 0.21728 * group.width, y: group.minY + 0.10120 * group.height))
        bezierPath.addCurve(to: CGPoint(x: group.minX + 0.18926 * group.width, y: group.minY + 0.10350 * group.height), controlPoint1: CGPoint(x: group.minX + 0.20861 * group.width, y: group.minY + 0.09500 * group.height), controlPoint2: CGPoint(x: group.minX + 0.19680 * group.width, y: group.minY + 0.09600 * group.height))
        bezierPath.addLine(to: CGPoint(x: group.minX + 0.10475 * group.width, y: group.minY + 0.18800 * group.height))
        bezierPath.addCurve(to: CGPoint(x: group.minX + 0.10231 * group.width, y: group.minY + 0.21583 * group.height), controlPoint1: CGPoint(x: group.minX + 0.09729 * group.width, y: group.minY + 0.19546 * group.height), controlPoint2: CGPoint(x: group.minX + 0.09625 * group.width, y: group.minY + 0.20720 * group.height))
        bezierPath.addLine(to: CGPoint(x: group.minX + 0.17621 * group.width, y: group.minY + 0.32154 * group.height))
        bezierPath.addCurve(to: CGPoint(x: group.minX + 0.14495 * group.width, y: group.minY + 0.39676 * group.height), controlPoint1: CGPoint(x: group.minX + 0.16306 * group.width, y: group.minY + 0.34535 * group.height), controlPoint2: CGPoint(x: group.minX + 0.15258 * group.width, y: group.minY + 0.37054 * group.height))
        bezierPath.addLine(to: CGPoint(x: group.minX + 0.01818 * group.width, y: group.minY + 0.41787 * group.height))
        bezierPath.addCurve(to: CGPoint(x: group.minX + 0.00000 * group.width, y: group.minY + 0.43930 * group.height), controlPoint1: CGPoint(x: group.minX + 0.00770 * group.width, y: group.minY + 0.41961 * group.height), controlPoint2: CGPoint(x: group.minX + 0.00000 * group.width, y: group.minY + 0.42870 * group.height))
        bezierPath.addLine(to: CGPoint(x: group.minX + 0.00000 * group.width, y: group.minY + 0.55887 * group.height))
        bezierPath.addCurve(to: CGPoint(x: group.minX + 0.01794 * group.width, y: group.minY + 0.58028 * group.height), controlPoint1: CGPoint(x: group.minX + 0.00000 * group.width, y: group.minY + 0.56941 * group.height), controlPoint2: CGPoint(x: group.minX + 0.00757 * group.width, y: group.minY + 0.57843 * group.height))
        bezierPath.addLine(to: CGPoint(x: group.minX + 0.14471 * group.width, y: group.minY + 0.60276 * group.height))
        bezierPath.addCurve(to: CGPoint(x: group.minX + 0.17597 * group.width, y: group.minY + 0.67798 * group.height), controlPoint1: CGPoint(x: group.minX + 0.15230 * group.width, y: group.minY + 0.62891 * group.height), controlPoint2: CGPoint(x: group.minX + 0.16278 * group.width, y: group.minY + 0.65411 * group.height))
        bezierPath.addLine(to: CGPoint(x: group.minX + 0.10116 * group.width, y: group.minY + 0.78261 * group.height))
        bezierPath.addCurve(to: CGPoint(x: group.minX + 0.10347 * group.width, y: group.minY + 0.81063 * group.height), controlPoint1: CGPoint(x: group.minX + 0.09499 * group.width, y: group.minY + 0.79124 * group.height), controlPoint2: CGPoint(x: group.minX + 0.09596 * group.width, y: group.minY + 0.80309 * group.height))
        bezierPath.addLine(to: CGPoint(x: group.minX + 0.18799 * group.width, y: group.minY + 0.89522 * group.height))
        bezierPath.addCurve(to: CGPoint(x: group.minX + 0.21584 * group.width, y: group.minY + 0.89765 * group.height), controlPoint1: CGPoint(x: group.minX + 0.19545 * group.width, y: group.minY + 0.90267 * group.height), controlPoint2: CGPoint(x: group.minX + 0.20721 * group.width, y: group.minY + 0.90372 * group.height))
        bezierPath.addLine(to: CGPoint(x: group.minX + 0.32172 * group.width, y: group.minY + 0.82350 * group.height))
        bezierPath.addCurve(to: CGPoint(x: group.minX + 0.39662 * group.width, y: group.minY + 0.85446 * group.height), controlPoint1: CGPoint(x: group.minX + 0.34549 * group.width, y: group.minY + 0.83657 * group.height), controlPoint2: CGPoint(x: group.minX + 0.37060 * group.width, y: group.minY + 0.84693 * group.height))
        bezierPath.addLine(to: CGPoint(x: group.minX + 0.41784 * group.width, y: group.minY + 0.98187 * group.height))
        bezierPath.addCurve(to: CGPoint(x: group.minX + 0.43926 * group.width, y: group.minY + 1.00000 * group.height), controlPoint1: CGPoint(x: group.minX + 0.41956 * group.width, y: group.minY + 0.99233 * group.height), controlPoint2: CGPoint(x: group.minX + 0.42862 * group.width, y: group.minY + 1.00000 * group.height))
        bezierPath.addLine(to: CGPoint(x: group.minX + 0.55883 * group.width, y: group.minY + 1.00000 * group.height))
        bezierPath.addCurve(to: CGPoint(x: group.minX + 0.58022 * group.width, y: group.minY + 0.98207 * group.height), controlPoint1: CGPoint(x: group.minX + 0.56938 * group.width, y: group.minY + 1.00000 * group.height), controlPoint2: CGPoint(x: group.minX + 0.57840 * group.width, y: group.minY + 0.99243 * group.height))
        bezierPath.addLine(to: CGPoint(x: group.minX + 0.60294 * group.width, y: group.minY + 0.85402 * group.height))
        bezierPath.addCurve(to: CGPoint(x: group.minX + 0.67752 * group.width, y: group.minY + 0.82283 * group.height), controlPoint1: CGPoint(x: group.minX + 0.62901 * group.width, y: group.minY + 0.84635 * group.height), controlPoint2: CGPoint(x: group.minX + 0.65399 * group.width, y: group.minY + 0.83591 * group.height))
        bezierPath.addLine(to: CGPoint(x: group.minX + 0.78416 * group.width, y: group.minY + 0.89763 * group.height))
        bezierPath.addCurve(to: CGPoint(x: group.minX + 0.81203 * group.width, y: group.minY + 0.89522 * group.height), controlPoint1: CGPoint(x: group.minX + 0.79281 * group.width, y: group.minY + 0.90374 * group.height), controlPoint2: CGPoint(x: group.minX + 0.80455 * group.width, y: group.minY + 0.90267 * group.height))
        bezierPath.addLine(to: CGPoint(x: group.minX + 0.89656 * group.width, y: group.minY + 0.81063 * group.height))
        bezierPath.addCurve(to: CGPoint(x: group.minX + 0.89882 * group.width, y: group.minY + 0.78254 * group.height), controlPoint1: CGPoint(x: group.minX + 0.90408 * group.width, y: group.minY + 0.80309 * group.height), controlPoint2: CGPoint(x: group.minX + 0.90506 * group.width, y: group.minY + 0.79120 * group.height))
        bezierPath.addLine(to: CGPoint(x: group.minX + 0.82277 * group.width, y: group.minY + 0.67696 * group.height))
        bezierPath.addCurve(to: CGPoint(x: group.minX + 0.85336 * group.width, y: group.minY + 0.60287 * group.height), controlPoint1: CGPoint(x: group.minX + 0.83566 * group.width, y: group.minY + 0.65348 * group.height), controlPoint2: CGPoint(x: group.minX + 0.84590 * group.width, y: group.minY + 0.62865 * group.height))
        bezierPath.addLine(to: CGPoint(x: group.minX + 0.98202 * group.width, y: group.minY + 0.58028 * group.height))
        bezierPath.addCurve(to: CGPoint(x: group.minX + 1.00000 * group.width, y: group.minY + 0.55887 * group.height), controlPoint1: CGPoint(x: group.minX + 0.99243 * group.width, y: group.minY + 0.57846 * group.height), controlPoint2: CGPoint(x: group.minX + 1.00000 * group.width, y: group.minY + 0.56941 * group.height))
        bezierPath.addLine(to: CGPoint(x: group.minX + 1.00000 * group.width, y: group.minY + 0.43930 * group.height))
        bezierPath.addCurve(to: CGPoint(x: group.minX + 0.98178 * group.width, y: group.minY + 0.41785 * group.height), controlPoint1: CGPoint(x: group.minX + 1.00002 * group.width, y: group.minY + 0.42865 * group.height), controlPoint2: CGPoint(x: group.minX + 0.99230 * group.width, y: group.minY + 0.41957 * group.height))
        bezierPath.close()
        bezierPath.move(to: CGPoint(x: group.minX + 0.50000 * group.width, y: group.minY + 0.65217 * group.height))
        bezierPath.addCurve(to: CGPoint(x: group.minX + 0.34781 * group.width, y: group.minY + 0.50000 * group.height), controlPoint1: CGPoint(x: group.minX + 0.41595 * group.width, y: group.minY + 0.65217 * group.height), controlPoint2: CGPoint(x: group.minX + 0.34781 * group.width, y: group.minY + 0.58404 * group.height))
        bezierPath.addCurve(to: CGPoint(x: group.minX + 0.50000 * group.width, y: group.minY + 0.34783 * group.height), controlPoint1: CGPoint(x: group.minX + 0.34781 * group.width, y: group.minY + 0.41596 * group.height), controlPoint2: CGPoint(x: group.minX + 0.41595 * group.width, y: group.minY + 0.34783 * group.height))
        bezierPath.addCurve(to: CGPoint(x: group.minX + 0.65219 * group.width, y: group.minY + 0.50000 * group.height), controlPoint1: CGPoint(x: group.minX + 0.58405 * group.width, y: group.minY + 0.34783 * group.height), controlPoint2: CGPoint(x: group.minX + 0.65219 * group.width, y: group.minY + 0.41596 * group.height))
        bezierPath.addCurve(to: CGPoint(x: group.minX + 0.50000 * group.width, y: group.minY + 0.65217 * group.height), controlPoint1: CGPoint(x: group.minX + 0.65219 * group.width, y: group.minY + 0.58404 * group.height), controlPoint2: CGPoint(x: group.minX + 0.58405 * group.width, y: group.minY + 0.65217 * group.height))
        bezierPath.close()
        white.setFill()
        bezierPath.fill()
    }

    //// Generated Images

    @objc dynamic public class func imageOfWatcher(imageSize: CGSize = CGSize(width: 200, height: 200)) -> UIImage {
        UIGraphicsBeginImageContextWithOptions(imageSize, false, 0)
            Player.drawWatcher(frame: CGRect(x: 0, y: 0, width: imageSize.width, height: imageSize.height))

        let imageOfWatcher = UIGraphicsGetImageFromCurrentImageContext()!
        UIGraphicsEndImageContext()

        return imageOfWatcher
    }

    @objc dynamic public class func imageOfFailed(imageSize: CGSize = CGSize(width: 50, height: 50)) -> UIImage {
        UIGraphicsBeginImageContextWithOptions(imageSize, false, 0)
            Player.drawFailed(frame: CGRect(x: 0, y: 0, width: imageSize.width, height: imageSize.height))

        let imageOfFailed = UIGraphicsGetImageFromCurrentImageContext()!
        UIGraphicsEndImageContext()

        return imageOfFailed
    }

    @objc dynamic public class func imageOfSettings(imageSize: CGSize = CGSize(width: 50, height: 50)) -> UIImage {
        UIGraphicsBeginImageContextWithOptions(imageSize, false, 0)
            Player.drawSettings(frame: CGRect(x: 0, y: 0, width: imageSize.width, height: imageSize.height))

        let imageOfSettings = UIGraphicsGetImageFromCurrentImageContext()!
        UIGraphicsEndImageContext()

        return imageOfSettings
    }

}
